config/routes.rb
Rails.application.routes.draw do
  
  post 'api/newmessage'

  resources :services, only: [:show, :edit, :update, :destro] do 
    resources :messages
  end

  devise_for :users
  resources :users, only: [:show, :edit, :destroy] do
  end

  root to: 'home#main'
  get 'home/main'
  get 'auth/twitter/callback' => 'sessions#create'
  get 'sessions/create'

end

app/models/service.rb
# == Schema Information
#
# Table name: services
#
#  id                  :integer          not null, primary key
#  provider            :string(255)
#  uid                 :string(255)
#  name                :string(255)
#  total_field         :text
#  user_id             :integer
#  created_at          :datetime
#  updated_at          :datetime
#  access_token        :text
#  access_token_secret :text
#  service_token       :text
#  tags                :text
#  email_alert         :boolean          default(FALSE)
#  automatic_follow    :boolean          default(TRUE)
#
class Service < ActiveRecord::Base
  ##-- Requirements and Concerns ---
  require 'securerandom'

  ##-- Constants--------------------

  ##-- Virtual Attributes ----------
  serialize :total_field

  ##-- Validations -----------------
  validates :provider, presence: true
  validates :name, presence: true
  validates :uid, presence: true
  validates :uid, uniqueness: true
  validates :service_token, uniqueness: true

  # validates :username, uniqueness: { case_sensitive: false }

  ##-- Callbacks -------------------
  after_save :create_tokens
  before_validation :create_service_token, :on => :create

  ##-- Associations ----------------
  # has_many :roles, dependent: :destroy
  # has_many :users, through: :memberships
  belongs_to :user
  has_many :messages, dependent: :destroy

  ##-- Scopes ----------------------
  # scope :active, -> { where(active: true) }

  ##-- Methods ---------------------

  # Method that returns the human identification for the service
  def full_name
    return self.provider.to_s + " (" + self.name.to_s + ")"
  end

  # Find or create the service
  def self.from_omniauth(auth, user)
    where(auth.slice("provider", "uid")).first || create_from_omniauth(auth, user)
  end

  # Create the service from the Oauth returned hash
  def self.create_from_omniauth(auth, user)
    create! do |service|
      service.provider = auth["provider"]
      service.uid = auth["uid"]
      service.name = auth["info"]["nickname"]
      service.total_field = auth.to_json
      service.user_id = user.id
    end
  end

  # Send Message through the service. Differentiate between the different provicer
  def send_message(message)
    if self.provider == "twitter"
    content = message.content.to_s
    url = message.url.to_s
    tags = message.tags_array
    person = message.person.to_s
    sender = self.service_api
    success = sender.send_tweet(content, url, tags, person)
    end

    if self.email_alert
      self.send_message_mail_to_user(message)
    end

    return success
  end

  # Test message
  def send_test
    if self.provider == "twitter"
      sender = TwitterSender.new(self.access_token, self.access_token_secret)
    sender.test_tweet
    end
  end

  # Test to follow topics
  def follow_relevant_people
    if !tags.to_s.empty? && self.automatic_follow
      if self.provider == "twitter"
        tags_array = self.tags.split(',')
      sender = self.service_api
      sender.follow_tweet_sender(tags_array)
      end
    end
  end

  def service_api
    if self.provider == "twitter"
      return TwitterSender.new(self.access_token, self.access_token_secret)
    end
  end

  # Return the global hash returned by the provider
  def properties
    JSON.parse(self.total_field)
  end

  # Refresh the service token
  def refresh_service_token
    token = SecureRandom.hex
    while(Service.find_by(service_token: token)) do
      token = SecureRandom.hex
    end
    self.update(:service_token => token)
  end

  # Callback to create service token
  def create_service_token
    token = SecureRandom.hex
    while(Service.find_by(service_token: token)) do
      token = SecureRandom.hex
    end
    self.service_token = token
  end

  # Callbacks to save the Access tokens
  def create_tokens
    if self.provider == "twitter"
      access_token = self.properties['credentials']['token']
      access_token_secret = self.properties['credentials']['secret']
      self.update_columns(access_token: access_token,access_token_secret: access_token_secret )
    end
  end

  # Mail to the user to confirm the sending of the message
  def send_message_mail_to_user(message)
    MessageMailer.new_message(self.user, message).deliver
  end

end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_service, only: [:show, :edit, :update, :destroy]
  respond_to :html
  def show
    @messages = @service.messages.order('created_at DESC').limit(5)
    respond_with(@service)
  end

  def edit
  end

  def update
    @service.update(service_params)
    respond_with(@service)
  end

  def destroy
    @service.destroy
    respond_with(@service)
  end

  private

  def set_service
    @service = current_user.services.find_by_id(params[:id])
    if !@service
      flash[:notice] = "Ce service n'est pas reconnu"
      redirect_to current_user
    end
  end

  def service_params
    params.require(:service).permit(:name, :tags, :automatic_follow, :email_alert)
  end
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/views/services/_form.html.erb
<%= form_for(service) do |f| %>
<% if service.errors.any? %>
<div id="error_explanation">
	<h2><%= pluralize(service.errors.count, "error") %> prohibited this service from being saved:</h2>

	<ul>
		<% service.errors.full_messages.each do |message| %>
		<li>
			<%= message %>
		</li>
		<% end %>
	</ul>
</div>
<% end %>

<div class="form-group">
	<%= f.label :name, "Name of the service. Usually provided by the social Network" %>
	<br>
	<%= f.text_field :name, :class => "form-control" %>
</div>

<div class="form-group">
	<%= f.label "Send alert on email after an automatic message ?" %>
	
	<%= f.check_box :email_alert %>
	
</div>
<div class="form-group">
	<%= f.label "Activate the automatic following of people tweeting on the tags" %>
	
	<%= f.check_box :automatic_follow %>
	
</div>
<div class="form-group">
	<%= f.label :tags, "Tags to follow" %> <i> Separate by commas</i>
	<br>
	<%= f.text_area :tags, :class => "form-control" %>
</div>

<div class="actions text-center">
	<% if service.new_record? %>
	<%= f.submit "Create", :class => "btn btn-success btn-lg" %>
	<% else %>
	<%= f.submit "Update", :class => "btn btn-success btn-lg" %>
	<% end %>
</div>
<% end %>

app/views/services/_service.html.erb
<div class="panel panel-default">
	<div class="panel-heading first-uppercase size-18">
		<b class=""><%= link_to service.full_name , service %></b>
	</div>
	<div class="panel-body">
		<b>Name of the account: </b><%= service.name %>
		<br />
		<b>Added date: </b><%= l service.created_at %>
		<br/>
		<strong>Service token : </strong> <%= service.service_token%></span>

	</div>
	<div class="panel-footer">
		Messages : <span class="label label-info size-14"><%= service.messages.size %></span>
	</div>
</div>

app/views/services/edit.html.erb
<div class="col-md-12">
	<h1 class="page-header text-center">Service Configuration <%= link_to @service.full_name, @service%></h1>

	<%= render 'form', service: @service %>

	<hr />

	<%= link_to 'Back to service page', @service, :class => "btn btn-warning" %>
</div>

app/views/services/index.html.erb
<h1 class="page-header text-center">Services</h1>

<table class="table">
	<thead>
		<tr>
			<th>Provider</th>
			<th>Uid</th>
			<th>Name</th>
			<th>Total field</th>
			<th>User</th>
			<th colspan="3"></th>
		</tr>
	</thead>

	<tbody>
		<% @services.each do |service| %>
		<tr>
			<td><%= service.provider %></td>
			<td><%= service.uid %></td>
			<td><%= service.name %></td>
			<td><%= service.total_field %></td>
			<td><%= service.user %></td>
			<td><%= link_to 'Show', service %></td>
			<td><%= link_to 'Edit', edit_service_path(service) %></td>
			<td><%= link_to 'Destroy', service, method: :delete, data: { confirm: 'Are you sure?' } %></td>
		</tr>
		<% end %>
	</tbody>
</table>

<br>

app/views/services/new.html.erb
<h1 class="page-header text-center">New Service</h1>

<%= render 'form', service: @service %>

<%= link_to 'Back', services_path, :class => "btn btn-warning" %>

app/views/services/show.html.erb
<div class="col-md-12">
	<h1 class="page-header text-center">Service connecté: <span class="text text-info"><%= @service.full_name %></span></h1>

	<div class="col-md-6 col-sm-12">
		<h2 class="page-header">Description</h2>
		<p>
			<strong>Social Network:</strong>
			<%= @service.provider %>
		</p>

		<p>
			<strong>Uid:</strong>
			<%= @service.uid %>
		</p>

		<p>
			<strong>Name of the account:</strong>
			<%= @service.name %>
		</p>

		<p>
			<strong>Account Token</strong>
			<br />
			Token :<%= @service.access_token %>
			<br />
			Secret: <%= @service.access_token_secret %>
		</p>
		<div class="alert alert-info">
			<strong>SocialPresence Service Token: </strong> <%= @service.service_token %>
		</div>
	</div>
	<div class="col-md-6 col-sm-12">
		<h2 class="page-header">Configuration</h2>
		<p>
			<strong>Email alert after message sent : </strong> <%= @service.email_alert%>
		</p>
		<p>
			<strong>Automatic Follow : </strong> <%= @service.automatic_follow%>
		</p>
		<p>
			<strong>Tags to follow for this service :</strong>
			<%= @service.tags %>
			<% if @service.tags.to_s.empty?%>
			NO TAGS ENTERED
			<%end %>
		</p>

		<%= link_to 'Configure', edit_service_path(@service), :class => "btn btn-warning"  %>
		<%= link_to 'Destroy the service', @service, method: :delete, data: { confirm: 'Are you sure?' }, :class => "btn btn-danger" %>
	</div>

	<div class="col-md-12 col-sm-12">
		<h2 class="page-header text-center"> Last 5 Messages sent <%= link_to "All the messages", service_messages_path(@service), class: "btn btn-info btn-lg"%></h2>
		<% @messages.each do |message| %>
		<%= render partial: "messages/message", locals:{message:message}%>
		<% end %>
	</div>
</div>