config/routes.rb
Rails.application.routes.draw do
  
  post 'api/newmessage'

  resources :services, only: [:show, :edit, :update, :destro] do 
    resources :messages
  end

  devise_for :users
  resources :users, only: [:show, :edit, :destroy] do
  end

  root to: 'home#main'
  get 'home/main'
  get 'auth/twitter/callback' => 'sessions#create'
  get 'sessions/create'

end

app/models/message.rb
# == Schema Information
#
# Table name: messages
#
#  id            :integer          not null, primary key
#  service_id    :integer
#  service_token :text
#  content       :text
#  url           :text
#  from_url      :text
#  tags          :text
#  created_at    :datetime
#  updated_at    :datetime
#  has_been_sent :boolean          default(FALSE)
#  from_api      :boolean          default(FALSE)
#  sent_time     :datetime
#  person        :string(255)
#

class Message < ActiveRecord::Base
  ##-- Requirements and Concerns ---

  ##-- Constants--------------------

  ##-- Virtual Attributes ----------

  ##-- Validations -----------------
  # validates :email, presence: true
  # validates :username, uniqueness: { case_sensitive: false }
  validates :content, presence: true
  validates :service, presence: true

  ##-- Callbacks -------------------
  after_create :send_message

  ##-- Associations ----------------
  # has_many :roles, dependent: :destroy
  # has_many :users, through: :memberships
  belongs_to :service

  ##-- Scopes ----------------------
  # scope :active, -> { where(active: true) }

  ##-- Methods ---------------------
  
  # Return an array of tags separated by ,
  def tags_array
    tags_array = self.tags.to_s.split(',')
  end
  
  # Callbacks after creation
  def send_message
    success = self.service.send_message(self)
    if success
      self.update_columns(has_been_sent: true, sent_time: DateTime.now )
    end
  end
  
  # Class method to create a message from the API
  def self.create_from_api(message_hash, service)
    content = message_hash[:content].to_s
    url = message_hash[:url].to_s
    tags = message_hash[:tags].to_s
    person = message_hash[:person].to_s
    service_id = service.id
    Message.create(:content => content, :url => url, :tags => tags, :service_id => service_id, :from_api => true, :person => person)
  end
  
  

end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_filter :authenticate_user!
  before_filter :get_service
  before_action :set_message, only: [:show, :edit, :update, :destroy]
  respond_to :html
  
  def index
    @messages = @service.messages.order('created_at DESC')
    respond_with(@messages)
  end

  def show
    respond_with(@service, @message)
  end

  def new
    @message = @service.messages.build()
    respond_with(@service, @message)
  end

  def edit
  end

  def create
    @message = @service.messages.build(message_params)
    @message.save
    respond_with(@service, @message)
  end

  def update
    @message.update(message_params)
    respond_with(@service, @message)
  end

  def destroy
    @message.destroy
    respond_with(@service, @message)
  end

  private

  def get_service
    @service = current_user.services.find_by_id(params[:service_id])
    if !@service
      flash[:notice] = "Ce service n'est pas reconnu"
      redirect_to current_user
    end
  end

  def set_message
    @message = @service.messages.find(params[:id])
  end

  def message_params
    params.require(:message).permit(:service_id, :service_token, :content, :url, :from_url, :tags)
  end
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/messages/_form.html.erb
<%= form_for([@service, message]) do |f| %>
<% if message.errors.any? %>
<div id="error_explanation">
	<h2><%= pluralize(message.errors.count, "error") %> prohibited this message from being saved:</h2>

	<ul>
		<% message.errors.full_messages.each do |message| %>
		<li>
			<%= message %>
		</li>
		<% end %>
	</ul>
</div>
<% end %>

<div class="form-group">
	<%= f.label :content %>
	<br>
	<%= f.text_area :content, :class => "form-control" %>
</div>
<div class="form-group">
	<%= f.label :url %>
	<br>
	<%= f.text_area :url, :class => "form-control" %>
</div>

<div class="form-group">
	<%= f.label :tags %>
	<br>
	<%= f.text_area :tags, :class => "form-control" %>
</div>
<div class="actions text-center">
	<% if message.new_record? %>
	<%= f.submit "Create", :class => "btn btn-success btn-lg" %>
	<% else %>
	<%= f.submit "Update", :class => "btn btn-success btn-lg" %>
	<% end %>
</div>
<% end %>

app/views/messages/_message.html.erb
<div class="panel panel-default">
	<div class="panel-heading first-uppercase size-18">
		<b class="">Received Date : <%= link_to message.created_at, service_message_path(message.service, message) %></b>
	</div>
	<div class="panel-body">
		<b>Service : </b><%= message.service.name %>
		<br />
		<b>Content: </b><%= message.content %>
		<br/>
		<strong>Sent ? </strong>
		<% if message.has_been_sent %>
		<span class="text text-success"><i class="fa fa-check-square"></i></span>
		<% else %>
		<span class="text text-danger"><i class="fa fa-close"></i></span>
		<% end %>

	</div>
</div>

app/views/messages/edit.html.erb
<h1 class="page-header text-center">Editing Message</h1>

<%= render 'form', message: @message %>

<%= link_to 'Show', service_message_path(@service, @message), :class => "btn btn-warning" %> |
<%= link_to 'Back', service_messages_path(@service), :class => "btn btn-info" %>

app/views/messages/index.html.erb
<div class="col-md-12">
	<h1 class="page-header text-center"><%= link_to @service.full_name, @service %> : All the messages sent<%= link_to 'New Message', new_service_message_path(@service), :class => "btn btn-success pull-right" %></h1>

	<table class="table">
		<thead>
			<tr>
				<th>DateTime</th>
				<th>Sent ?</th>
				<th>Content</th>
				<th>Url</th>
				<th>Tags</th>
				<th colspan="3"></th>
			</tr>
		</thead>

		<tbody>
			<% @messages.each do |message| %>
			<tr>
				<td><%= l message.created_at %></td>
				<td> <% if message.has_been_sent %> <span class="text text-success"><i class="fa fa-check-square"></i></span> <% else %> <span class="text text-danger"><i class="fa fa-close"></i></span> <% end %> </td>
				<td><%= message.content %></td>
				<td><%= message.url %></td>

				<td><%= message.tags %></td>
				<td><%= link_to 'Show', service_message_path(@service, message) %></td>
				<td><%= link_to 'Edit', edit_service_message_path(@service, message) %></td>
				<td><%= link_to 'Destroy', service_message_path(@service, message), method: :delete, data: { confirm: 'Are you sure?' } %></td>
			</tr>
			<% end %>
		</tbody>
	</table>

	<br>

	
</div>

app/views/messages/new.html.erb
<h1 class="page-header text-center">New Message</h1>

<%= render 'form', message: @message %>

<%= link_to 'Back', service_messages_path(@service), :class => "btn btn-warning" %>

app/views/messages/show.html.erb
<div class="col-md-12">
	<h1 class="page-header text-center">Message</h1>

	<p>
		<strong>Service:</strong>
		<%= link_to @message.service.full_name, @message.service %>
	</p>

	<p>
		<strong>Service token:</strong>
		<%= @message.service_token %>
	</p>

	<p>
		<strong>Recu le:</strong>
		<%= @message.created_at %>
	</p>

	<p>
		<strong>Content:</strong>
		<%= @message.content %>
	</p>

	<p>
		<strong>Url:</strong>
		<%= @message.url %>
	</p>

	<p>
		<strong>From url:</strong>
		<%= @message.from_url %>
	</p>

	<p>
		<strong>Tags:</strong>
		<%= @message.tags %>
	</p>

	<p>
		<strong>Person:</strong>
		<%= @message.person %>
	</p>

	<p>
		<strong>Envoyé ? :</strong> <%= @message.has_been_sent %>
		<% if @message.has_been_sent %>
		<br />
		<strong>Date d'envoi :</strong> <%= @message.sent_time %>
		<% end%>
	</p>

	<%= link_to 'Edit', edit_service_message_path(@service, @message), :class => "btn btn-warning"  %> |
	<%= link_to 'Back', service_messages_path(@service), :class => "btn btn-primary"  %>
</div>